-- ==============================================================================
-- SUPABASE SCHEMA FOR JAPAN SHOP (C3 SHOP)
-- Copy toàn bộ nội dung file này và dán vào Supabase SQL Editor rồi bấm "Run".
-- ==============================================================================

-- 1. BẢNG DANH MỤC (categories)
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    banner_gradient TEXT DEFAULT 'from-indigo-600 to-violet-700',
    badge_color TEXT DEFAULT 'bg-indigo-500',
    icon_name TEXT DEFAULT 'SparklesIcon',
    item_count_text TEXT DEFAULT '0 sản phẩm',
    subcategories JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. BẢNG SẢN PHẨM (products)
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    image TEXT NOT NULL,
    image_bg TEXT DEFAULT '',
    price NUMERIC NOT NULL DEFAULT 0,
    old_price NUMERIC,
    rating NUMERIC DEFAULT 5.0,
    reviews INTEGER DEFAULT 0,
    tag TEXT,
    stock INTEGER DEFAULT 0,
    ingredients TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Cập nhật thêm cột ingredients nếu bảng đã tạo từ trước
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS ingredients TEXT DEFAULT '';

-- 3. BẢNG LIÊN KẾT DANH MỤC - SẢN PHẨM (category_products)
CREATE TABLE IF NOT EXISTS public.category_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_category_product UNIQUE (category_id, product_id)
);

-- 4. BẢNG THỨ TỰ HIỂN THỊ SẢN PHẨM NỔI BẬT (product_orders)
CREATE TABLE IF NOT EXISTS public.product_orders (
    product_id TEXT PRIMARY KEY,
    order_num INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- BẬT ROW LEVEL SECURITY (RLS) & TẠO CHÍNH SÁCH TRUY CẬP (POLICIES)
-- ==============================================================================

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_orders ENABLE ROW LEVEL SECURITY;

-- Cho phép tất cả mọi người đọc (SELECT) dữ liệu sản phẩm, danh mục
DROP POLICY IF EXISTS "Public categories are viewable by everyone" ON public.categories;
CREATE POLICY "Public categories are viewable by everyone" ON public.categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public products are viewable by everyone" ON public.products;
CREATE POLICY "Public products are viewable by everyone" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public category_products are viewable by everyone" ON public.category_products;
CREATE POLICY "Public category_products are viewable by everyone" ON public.category_products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public product_orders are viewable by everyone" ON public.product_orders;
CREATE POLICY "Public product_orders are viewable by everyone" ON public.product_orders FOR SELECT USING (true);

-- Cho phép quyền Thêm/Sửa/Xóa qua Anon Key (Được bảo vệ bởi giao diện Admin Passkey trên Frontend)
DROP POLICY IF EXISTS "Enable insert for all" ON public.categories;
CREATE POLICY "Enable insert for all" ON public.categories FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for all" ON public.categories;
CREATE POLICY "Enable update for all" ON public.categories FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Enable delete for all" ON public.categories;
CREATE POLICY "Enable delete for all" ON public.categories FOR DELETE USING (true);

DROP POLICY IF EXISTS "Enable insert for all" ON public.products;
CREATE POLICY "Enable insert for all" ON public.products FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for all" ON public.products;
CREATE POLICY "Enable update for all" ON public.products FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Enable delete for all" ON public.products;
CREATE POLICY "Enable delete for all" ON public.products FOR DELETE USING (true);

DROP POLICY IF EXISTS "Enable insert for all" ON public.category_products;
CREATE POLICY "Enable insert for all" ON public.category_products FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for all" ON public.category_products;
CREATE POLICY "Enable update for all" ON public.category_products FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Enable delete for all" ON public.category_products;
CREATE POLICY "Enable delete for all" ON public.category_products FOR DELETE USING (true);

DROP POLICY IF EXISTS "Enable insert for all" ON public.product_orders;
CREATE POLICY "Enable insert for all" ON public.product_orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for all" ON public.product_orders;
CREATE POLICY "Enable update for all" ON public.product_orders FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Enable delete for all" ON public.product_orders;
CREATE POLICY "Enable delete for all" ON public.product_orders FOR DELETE USING (true);

-- Làm mới schema cache của Supabase PostgREST
NOTIFY pgrst, 'reload schema';
